In [13]:
from bs4 import BeautifulSoup as bs
import requests
import numpy as np

In [2]:
scrape_url = 'https://stats.espncricinfo.com/ci/engine/records/averages/bowling.html?id=14452;type=tournament'
r =  requests.get(scrape_url)

#Convert to a beautiful soup object
soup = bs(r.content)

#print out the html
contents = soup.prettify()
print(contents)

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- hostname: web05, edition-view: , country: unknown, cluster: www, created: 2022-07-13 03:55:16 -->
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/">
 <head>
  <script type="text/javascript">
   var _sf_startpt=(new Date()).getTime()
  </script>
  <meta content="ZxdgH3XglRg0Bsy-Ho2RnO3EE4nRs53FloLS6fkt_nc" name="google-site-verification"/>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>
  <title>
   Indian Premier League, 2022 Cricket Team Records &amp; Stats | ESPNcricinfo.com
  </title>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
  <meta content="Records,  / , Indian Premier League, 2022,  / , Bowling averages records, stats, bowling, batting, wicket keeper" name="keywords"/>
  <meta content="Read about Records,  / , Indian Premier League, 2022,  / , Bowling averages Cricket Team Records only on ESPNcricinfo.com. Check the Stats &amp; Records of Records,  / , Indian Premier League, 2022,  / , Bowling averages Players in ✓ Wicket keeper ✓ Batting ✓ Bowling" name="description"/>
  <!--[if IE 9]>
<script language="javascript" type="text/javascript">
function fnCreateJumpList(iScenario) {
fnClearJumpList();
window.external.msSiteModeCreateJumpList("Quick Links")
window.external.msSiteModeAddJumpListItem('World Cup Super League', 'https://www.espncricinfo.com/ci/content/current/series/1227837.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('World Test Championship', 'https://www.espncricinfo.com/ci/content/current/series/1268315.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Women's Championship', 'https://www.espncricinfo.com/ci/content/current/series/1308225.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('TNPL 2022', 'https://www.espncricinfo.com/ci/content/current/series/1312873.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('County Div2', 'https://www.espncricinfo.com/ci/content/current/series/1310355.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('County Div1', 'https://www.espncricinfo.com/ci/content/current/series/1297650.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Vitality Blast', 'https://www.espncricinfo.com/ci/content/current/series/1297657.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('SA-W in ENG', 'https://www.espncricinfo.com/ci/content/current/series/1289256.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('IND-W in SL', 'https://www.espncricinfo.com/ci/content/current/series/1319706.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('West Indies v Bangladesh', 'https://www.espncricinfo.com/ci/content/current/series/1317143.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Sri Lanka v Pakistan', 'https://www.espncricinfo.com/ci/content/current/series/1320948.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Sri Lanka v Australia', 'https://www.espncricinfo.com/ci/content/current/series/1307289.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('England v India (2022)', 'https://www.espncricinfo.com/ci/content/current/series/1276893.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('England v India (5th Test)', 'https://www.espncricinfo.com/ci/content/current/series/1239527.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Ireland v New Zealand', 'https://www.espncricinfo.com/ci/content/current/series/1307472.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('CPL 2022', 'https://www.espncricinfo.com/ci/content/current/series/1320379.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('WCPL 2022', 'https://www.espncricinfo.com/ci/content/current/series/1323138.html', 'https://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeShowJumpList();
}
function fnClearJumpList() {
window.external.msSiteModeClearJumplist();
}
</script>

<meta name="msapplication-task" content="name=Live Scores;action-uri=https://www.espncricinfo.com/ci/engine/current/match/scores/live.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Latest News;action-uri=https://www.espncricinfo.com/ci/content/current/story/news.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Fixtures;action-uri=https://www.espncricinfo.com/ci/content/current/match/fixtures/index.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Results;action-uri=https://www.espncricinfo.com/ci/engine/current/match/scores/recent.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Photos;action-uri=https://www.espncricinfo.com/ci/content/current/image/index.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Audio/Video;action-uri=https://www.espncricinfo.com/ci/content/video_audio/index.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>
<script language="javascript" type="text/javascript">
        fnCreateJumpList(2);
</script>
<![endif]-->
  <meta content="index, follow" name="robots"/>
  <meta content="index, follow" name="googlebot"/>
  <meta content="Indian Premier League, 2022 Cricket Team Records &amp; Stats | ESPNcricinfo.com" property="og:title"/>
  <meta content="Read about Records,  / , Indian Premier League, 2022,  / , Bowling averages Cricket Team Records only on ESPNcricinfo.com. Check the Stats &amp; Records of Records,  / , Indian Premier League, 2022,  / , Bowling averages Players in ✓ Wicket keeper ✓ Batting ✓ Bowling" property="og:description"/>
  <link href="https://stats.espncricinfo.com/ci/engine/records/averages/bowling.html?id=14452&amp;type=tournament" rel="canonical"/>
  <meta content="https://stats.espncricinfo.com/ci/engine/records/averages/bowling.html?id=14452&amp;type=tournament" property="og:url"/>
  <meta content="article" property="og:type"/>
  <meta content="507509800,543647230,521294616,502164596,548845180,100000100658108,738070288" property="fb:admins"/>
  <link href="https://i.imgci.com/espncricinfo/facebook.jpg" rel="image_src"/>
  <meta content="https://i.imgci.com/espncricinfo/facebook.jpg" property="og:image"/>
  <meta name="twitter:site" value="@espncricinfo"/>
  <meta name="twitter:creator" value="@espncricinfo"/>
  <meta content="Indian Premier League, 2022 Cricket Team Records &amp; Stats | ESPNcricinfo.com" name="twitter:title"/>
  <meta content="Read about Records,  / , Indian Premier League, 2022,  / , Bowling averages Cricket Team Records only on ESPNcricinfo.com. Check the Stats &amp; Records of Records,  / , Indian Premier League, 2022,  / , Bowling averages Players in ✓ Wicket keeper ✓ Batting ✓ Bowling" name="twitter:description"/>
  <meta content="https://i.imgci.com/espncricinfo/twitter.jpg" property="twitter:image:src"/>
  <link href="https://a.espncdn.com/espncricinfo/favicon.ico" rel="shortcut icon"/>
  <link href="https://a.espncdn.com/espncricinfo/favicon.png" rel="icon" type="image/png"/>
  <link href="https://a.espncdn.com/espncricinfo/favicon.gif" rel="icon" type="image/gif"/>
  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-57x57.min.png" rel="apple-touch-icon"/>
  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-57x57.min.png" rel="apple-touch-icon-precomposed"/>
  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-72x72.min.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>
  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-114x114.min.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>
  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-152x152.min.png" rel="apple-touch-icon-precomposed" sizes="152x152"/>
  <script language="javascript" type="text/javascript">
   let isApp = false;
    if (window.CleverTap) {
        isApp = true;
    } else if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.clevertap) {
        isApp = true;
    }

    window.injectScript = function(src, opts) {
        (function() {
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.async = false;
        script.src = src;
        if(opts && typeof opts.id !== "undefined") script.id = opts.id;
        if(opts && typeof opts.async !== "undefined") script.async = opts.async;
        if(opts && typeof opts.defer !== "undefined") script.defer = opts.defer;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(script, s);
        })();
    };

    if (!isApp) {

            window.injectScript('https://dcf.espn.com/TWDC-DTCI/prod/Bootstrap.js');

    }
  </script>
  <meta content="260890547115" property="fb:app_id"/>
  <meta content="Cricinfo" property="og:site_name"/>
  <!-- Cricinfo Global News RSS feed link -->
  <link href="/rss/content/story/feeds/0.xml" rel="alternate" title="Global News RSS Feed" type="application/rss+xml"/>
  <link href="/rss/livescores.xml" rel="alternate" title="Cricinfo live scores RSS feed" type="application/rss+xml"/>
  <link charset="utf-8" href="https://a.espncdn.com/combiner/c?css=fonts/bentonsans.css,fonts/bentonsansbold.css,fonts/bentonsanslight.css,fonts/bentonsansmedium.css,fonts/bentonsanscond.css,fonts/bentonsanscondbold.css,fonts/bentonsanscondmedium.css" media="screen" rel="stylesheet" type="text/css"/>
  <link charset="utf-8" href="https://i.imgci.com/navigation/cricinfo/ci/assets/css/main_nav.css?v=1616584657" media="screen" rel="stylesheet" type="text/css"/>
  <link charset="utf-8" href="https://i.imgci.com/navigation/cricinfo/ci/assets/css/sub_nav.css?v=1616584657" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://i.imgci.com/navigation/cricinfo/ci/global.0.0.1.css?1602154871" rel="stylesheet" type="text/css"/>
  <script language="javascript" type="text/javascript">
   if(navigator.userAgent.indexOf('Linux') != -1) {
		var linux = '/navigation/cricinfo/ci/global_linux.css?1602154873';
		var linuxcss=document.createElement("link");
		linuxcss.setAttribute("rel", "stylesheet");
		linuxcss.setAttribute("type", "text/css");
		linuxcss.setAttribute("href", linux);
		document.getElementsByTagName("head")[0].appendChild(linuxcss);
	}
  </script>
  <script language="javascript" src="https://i.imgci.com/navigation/cricinfo/ci/jquery-1.7.2.min.js" type="text/javascript">
  </script>
  <script language="javascript" src="https://i.imgci.com/navigation/cricinfo/ci/default.js?1602154872" type="text/javascript">
  </script>
  <script src="https://a.espncdn.com/combiner/c?js=jquery-1.7.1.js,plugins/jquery.metadata.js,plugins/jquery.pubsub.r5.js,plugins/ba-debug-0.4.js,espn.l10n.r12.js,espn.core.duo.r55.js,espn.storage.r6.js,espn.geo.r2.js">
  </script>
  <link href="https://a.espncdn.com/players/web-player-bundle/3.2.13/espn-web-player-bundle.css" rel="stylesheet"/>
  <!-- VOD Shim starts -->
  <script src="https://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery-2.0.2.min.js">
  </script>
  <script src="https://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery.cookie-1.4.1.js">
  </script>
  <script src="https://a.espncdn.com/players/web-player-bundle/3.2.38/espn-web-player-bundle.js">
  </script>
  <script src="https://i.imgci.com/navigation/cricinfo/ci/videoplayer/dtciplayer.js">
  </script>
  <!-- VOD Shim ends -->
  <script language="javascript" type="text/javascript">
   if (typeof $ === 'undefined'){
		var $ = jQuery;
	}
	ord=Math.random()*10000000000000000;
	var ad_counter = 1;

	cqanswer = '99';
	location_country = 'unknown';
	location_cluster = 'www';
  </script>
  <script src="https://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery.cookie-1.4.1.js">
  </script>
  <style type="text/css">
   .video-play-button{background: url(https://i.imgci.com/espncricinfo/video/play-icon.png) no-repeat left bottom;bottom: 10px;left: 10px;position: absolute;right: 0px;text-shadow: none;top: 0px;width: 100%;background-size: 50px auto;opacity: .6;color: transparent;cursor:pointer;}
.video-play-button:hover{opacity: 1;}
  </style>
  <meta content="ESPNcricinfo" name="application-name"/>
  <meta content="#266ab4" name="msapplication-TileColor"/>
  <meta content="https://i.imgci.com/espncricinfo/6b245241-3938-499c-8c79-9b80f97bed96.png" name="msapplication-TileImage"/>
  <script type="text/javascript">
   window.s_account = "wdgespcricinfo,wdgespge";
  </script>
  <!-- Load GPT JavaScript library used by DFP -->
  <script type="text/javascript">
   var googletag = googletag || {};
  googletag.cmd = googletag.cmd || [];
  (function() {
    var gads = document.createElement("script");
    gads.async = true;
    gads.type = "text/javascript";
    var useSSL = true;
    // var useSSL = "https:" == document.location.protocol;
    gads.src = (useSSL ? "https:" : "http:") + "//www.googletagservices.com/tag/js/gpt.js";
    var node =document.getElementsByTagName("script")[0];
    node.parentNode.insertBefore(gads, node);
   })();
  </script>
  <script src="https://a.espncdn.com/combiner/c?js=swfobject/2.2/swfobject.js?minify=false" type="text/javascript">
  </script>
  <style>
   .espni-ad-slot{line-height: 0;}
pre.gpt-debug{padding: 10px; background: burlywood;}
  </style>
  <script type="text/javascript">
   var ad_setting = {"adtar":"","kvbrand":"ci","kvcluster":"www","kvnavtype":"records","kvpt":"stats","kvsite":"stats","networkid":"21783347309","path":"/21783347309/espn.cricinfo.com/stats","sp":"cricinfo","template":"desktop","template_type":"non_responsive","tstAdTar":""}; var __GPTenabled = true;
  window.espn = window.espn || {};
  window.espn.ads = window.espn.ads || {};
  window.espn.ads.config = window.espn.ads.config || {};
  window.espn.ads.config.level = "espn.cricinfo.com/stats";
  </script>
  <style>
   .vjs-logolink.hide{display:none;}
  </style>
 </head>
 <body id="cric_old_template">
  <section class="mainnav_wrap" id="mainnav_wrap">
   <div class="nav_inner" id="nav_inner">
    <div class="nav_btn" id="nav_btn">
     <span class="back-icon-svg">
      <svg id="Capa_1" style="enable-background:new 0 0 31.494 31.494;" version="1.1" viewbox="0 0 31.494 31.494" x="0px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" y="0px">
       <path d="M10.273,5.009c0.444-0.444,1.143-0.444,1.587,0c0.429,0.429,0.429,1.143,0,1.571l-8.047,8.047h26.554 c0.619,0,1.127,0.492,1.127,1.111c0,0.619-0.508,1.127-1.127,1.127H3.813l8.047,8.032c0.429,0.444,0.429,1.159,0,1.587 c-0.444,0.444-1.143,0.444-1.587,0l-9.952-9.952c-0.429-0.429-0.429-1.143,0-1.571L10.273,5.009z" style="fill:#FFFFFF;">
       </path>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
       <g>
       </g>
      </svg>
     </span>
    </div>
    <div class="ci_logo" id="ci_logo">
     <a href="/">
      <img src="https://www.espncricinfo.com/static/images/logo.png"/>
      <span class="logo_txt">
       ESPN Cricinfo
      </span>
     </a>
    </div>
    <nav class="main_nav" data-role="none" id="main_nav">
     <ul class="nav_grp" data-role="none" id="nav_grp">
      <li class="nav_grpitm nav_live_scores">
       <a href="/live-cricket-score" name="&amp;lpos=header_livescores">
        Live Scores
       </a>
       <div class="nav_grp_lvl1 main_nav_options dd_wrap">
        <ul class="sub_nav" data-role="none">
         <li class="sub_nav_item">
          <a href="/live-cricket-score" name="&amp;lpos=header_livescores">
           Live Scores Home
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="https://www.espncricinfo.com/ci/engine/match/index.html?view=week" name="&amp;lpos=header_livescores">
           Week view
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="https://www.espncricinfo.com/ci/engine/series/index.html?view=month" name="&amp;lpos=header_livescores">
           Month view
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="https://www.espncricinfo.com/ci/engine/series/index.html?view=season" name="&amp;lpos=header_livescores">
           Season view
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="https://www.espncricinfo.com/ci/engine/match/index.html?view=calendar" name="&amp;lpos=header_livescores">
           International calendar
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="https://www.espncricinfo.com/ci/engine/match/scores/desktop.html" name="&amp;lpos=header_livescores">
           Desktop Scoreboard
          </a>
         </li>
        </ul>
       </div>
      </li>
      <li class="nav_grpitm nav_series">
       <a href="https://www.espncricinfo.com/ci/content/match/fixtures_futures.html" name="&amp;lpos=header_series">
        Series
       </a>
       <div class="nav_grp_lvl1 main_nav_options dd_wrap">
        <ul class="sub_nav" data-role="none">
         <li class="sub_nav_item">
          <a href="/series/india-in-england-2022-1276893" name="&amp;lpos=header_series">
           England v India
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/australia-in-sri-lanka-2022-1307289" name="&amp;lpos=header_series">
           Sri Lanka v Australia
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/bangladesh-tour-of-west-indies-2022-1317143" name="&amp;lpos=header_series">
           West Indies v Bangladesh
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/south-africa-in-england-2022-1276896" name="&amp;lpos=header_series">
           England v South Africa
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/pakistan-tour-in-sri-lanka-2022-1320948" name="&amp;lpos=header_series">
           Sri Lanka v Pakistan
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/india-in-west-indies-2022-1317885" name="&amp;lpos=header_series">
           West Indies v India
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/new-zealand-in-ireland-2022-1307472" name="&amp;lpos=header_series">
           Ireland v New Zealand
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/ireland-tri-nation-women-s-t20i-series-2022-1317631" name="&amp;lpos=header_series">
           IRE Tri-Series (Women)
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/series/india-women-in-sri-lanka-2022-1319706" name="&amp;lpos=header_series">
           IND-W in Sri Lanka

In [3]:
most_runs = soup.find(class_ = "engineTable")
print(most_runs.prettify())

<table class="engineTable">
 <caption>
  Bowling averages
 </caption>
 <thead>
  <tr class="head">
   <th class="left" nowrap="nowrap" title="player name">
    Player
   </th>
   <th class="padAst" nowrap="nowrap" title="matches played">
    Mat
   </th>
   <th nowrap="nowrap" title="innings bowled">
    Inns
   </th>
   <th nowrap="nowrap" title="overs bowled">
    Overs
   </th>
   <th nowrap="nowrap" title="maidens earned">
    Mdns
   </th>
   <th nowrap="nowrap" title="runs conceded">
    Runs
   </th>
   <th nowrap="nowrap" title="wickets taken">
    Wkts
   </th>
   <th nowrap="nowrap" title="best innings bowling">
    BBI
   </th>
   <th nowrap="nowrap" title="bowling average">
    Ave
   </th>
   <th nowrap="nowrap" title="economy rate">
    Econ
   </th>
   <th nowrap="nowrap" title="bowling strike rate">
    SR
   </th>
   <th nowrap="nowrap" title="four wkts in an inns">
    4
   </th>
   <th nowrap="nowrap" title="five wkts in an inns">
    5
   </th>
   <th nowrap="nowrap" title="catches taken">
    Ct
   </th>
   <th nowrap="nowrap" title="stumpings made">
    St
   </th>
  </tr>
 </thead>
 <tbody>
  <tr class="data2" data-days="738612">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/360911.html">
     VR Aaron
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    5.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    52
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    2/45
   </td>
   <td nowrap="nowrap">
    26.00
   </td>
   <td nowrap="nowrap">
    10.40
   </td>
   <td nowrap="nowrap">
    15.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738612">
   <td colspan="15">
    (Gujarat Titans)
   </td>
  </tr>
  <tr class="data2" data-days="738645">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/398666.html">
     SA Abbott
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    4.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    47
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1/47
   </td>
   <td nowrap="nowrap">
    47.00
   </td>
   <td nowrap="nowrap">
    11.75
   </td>
   <td nowrap="nowrap">
    24.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738645">
   <td colspan="15">
    (Sunrisers Hyderabad)
   </td>
  </tr>
  <tr class="data2" data-days="738614">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1175485.html">
     Abdul Samad
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    8
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    8.00
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738614">
   <td colspan="15">
    (Sunrisers Hyderabad)
   </td>
  </tr>
  <tr class="data2" data-days="738662">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1070183.html">
     Abhishek Sharma
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    14
   </td>
   <td nowrap="nowrap">
    3
   </td>
   <td nowrap="nowrap">
    4.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    38
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    9.50
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738662">
   <td colspan="15">
    (Sunrisers Hyderabad)
   </td>
  </tr>
  <tr class="data2" data-days="738662">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/398438.html">
     MA Agarwal
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    13
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    10
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738662">
   <td colspan="15">
    (Punjab Kings)
   </td>
  </tr>
  <tr class="data2" data-days="738661">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/942645.html">
     KK Ahmed
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    10
   </td>
   <td nowrap="nowrap">
    10
   </td>
   <td nowrap="nowrap">
    39.1
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    315
   </td>
   <td nowrap="nowrap">
    16
   </td>
   <td nowrap="nowrap">
    3/25
   </td>
   <td nowrap="nowrap">
    19.68
   </td>
   <td nowrap="nowrap">
    8.04
   </td>
   <td nowrap="nowrap">
    14.6
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738661">
   <td colspan="15">
    (Delhi Capitals)
   </td>
  </tr>
  <tr class="data2" data-days="738622">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1176959.html">
     Akash Deep
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    18.5
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    205
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    3/45
   </td>
   <td nowrap="nowrap">
    41.00
   </td>
   <td nowrap="nowrap">
    10.88
   </td>
   <td nowrap="nowrap">
    22.6
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738622">
   <td colspan="15">
    (Royal Challengers Bangalore)
   </td>
  </tr>
  <tr class="data2" data-days="738660">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/8917.html">
     MM Ali
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    10
   </td>
   <td nowrap="nowrap">
    10
   </td>
   <td nowrap="nowrap">
    23.5
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    158
   </td>
   <td nowrap="nowrap">
    8
   </td>
   <td nowrap="nowrap">
    3/13
   </td>
   <td nowrap="nowrap">
    19.75
   </td>
   <td nowrap="nowrap">
    6.62
   </td>
   <td nowrap="nowrap">
    17.8
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738660">
   <td colspan="15">
    (Chennai Super Kings)
   </td>
  </tr>
  <tr class="data2" data-days="738626">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/670013.html">
     FA Allen
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    4.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    46
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1/46
   </td>
   <td nowrap="nowrap">
    46.00
   </td>
   <td nowrap="nowrap">
    11.50
   </td>
   <td nowrap="nowrap">
    24.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738626">
   <td colspan="15">
    (Mumbai Indians)
   </td>
  </tr>
  <tr class="data2" data-days="738625">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1254269.html">
     Aman Hakim Khan
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    1.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    13
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    13.00
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738625">
   <td colspan="15">
    (Kolkata Knight Riders)
   </td>
  </tr>
  <tr class="data2" data-days="738612">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/851261.html">
     Anmolpreet Singh
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738612">
   <td colspan="15">
    (Mumbai Indians)
   </td>
  </tr>
  <tr class="data2" data-days="738633">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1123073.html">
     Anuj Rawat
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    8
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738633">
   <td colspan="15">
    (Royal Challengers Bangalore)
   </td>
  </tr>
  <tr class="data2" data-days="738630">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1209292.html">
     VG Arora
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    17.5
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    164
   </td>
   <td nowrap="nowrap">
    3
   </td>
   <td nowrap="nowrap">
    2/21
   </td>
   <td nowrap="nowrap">
    54.66
   </td>
   <td nowrap="nowrap">
    9.19
   </td>
   <td nowrap="nowrap">
    35.6
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738630">
   <td colspan="15">
    (Punjab Kings)
   </td>
  </tr>
  <tr class="data2" data-days="738662">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1125976.html">
     Arshdeep Singh
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    14
   </td>
   <td nowrap="nowrap">
    14
   </td>
   <td nowrap="nowrap">
    50.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    385
   </td>
   <td nowrap="nowrap">
    10
   </td>
   <td nowrap="nowrap">
    3/37
   </td>
   <td nowrap="nowrap">
    38.50
   </td>
   <td nowrap="nowrap">
    7.70
   </td>
   <td nowrap="nowrap">
    30.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    4
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738662">
   <td colspan="15">
    (Punjab Kings)
   </td>
  </tr>
  <tr class="data2" data-days="738649">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/528067.html">
     M Ashwin
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    8
   </td>
   <td nowrap="nowrap">
    8
   </td>
   <td nowrap="nowrap">
    29.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    228
   </td>
   <td nowrap="nowrap">
    9
   </td>
   <td nowrap="nowrap">
    2/14
   </td>
   <td nowrap="nowrap">
    25.33
   </td>
   <td nowrap="nowrap">
    7.86
   </td>
   <td nowrap="nowrap">
    19.3
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738649">
   <td colspan="15">
    (Mumbai Indians)
   </td>
  </tr>
  <tr class="data2" data-days="738669">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/26421.html">
     R Ashwin
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    17
   </td>
   <td nowrap="nowrap">
    17
   </td>
   <td nowrap="nowrap">
    67.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    503
   </td>
   <td nowrap="nowrap">
    12
   </td>
   <td nowrap="nowrap">
    3/17
   </td>
   <td nowrap="nowrap">
    41.91
   </td>
   <td nowrap="nowrap">
    7.50
   </td>
   <td nowrap="nowrap">
    33.5
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738669">
   <td colspan="15">
    (Rajasthan Royals)
   </td>
  </tr>
  <tr class="data2" data-days="738665">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/694211.html">
     Avesh Khan
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    13
   </td>
   <td nowrap="nowrap">
    13
   </td>
   <td nowrap="nowrap">
    47.4
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    416
   </td>
   <td nowrap="nowrap">
    18
   </td>
   <td nowrap="nowrap">
    4/24
   </td>
   <td nowrap="nowrap">
    23.11
   </td>
   <td nowrap="nowrap">
    8.72
   </td>
   <td nowrap="nowrap">
    15.8
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738665">
   <td colspan="15">
    (Lucknow Super Giants)
   </td>
  </tr>
  <tr class="data2" data-days="738655">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1151270.html">
     A Badoni
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    13
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    2.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    11
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    1/5
   </td>
   <td nowrap="nowrap">
    5.50
   </td>
   <td nowrap="nowrap">
    5.50
   </td>
   <td nowrap="nowrap">
    6.0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    9
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738655">
   <td colspan="15">
    (Lucknow Super Giants)
   </td>
  </tr>
  <tr class="data2" data-days="738662">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/297433.html">
     JM Bairstow
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    11
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738662">
   <td colspan="15">
    (Punjab Kings)
   </td>
  </tr>
  <tr class="data2" data-days="738623">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/732291.html">
     Basil Thampi
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    16.0
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    152
   </td>
   <td nowrap="nowrap">
    5
   </td>
   <td nowrap="nowrap">
    3/35
   </td>
   <td nowrap="nowrap">
    30.40
   </td>
   <td nowrap="nowrap">
    9.50
   </td>
   <td nowrap="nowrap">
    19.2
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    1
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738623">
   <td colspan="15">
    (Mumbai Indians)
   </td>
  </tr>
  <tr class="data2" data-days="738611">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/1292502.html">
     RA Bawa
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>
   <td class="padDp1" nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    0
   </td>
   <td nowrap="nowrap">
    0
   </td>
  </tr>
  <tr class="note" data-days="738611">
   <td colspan="15">
    (Punjab Kings)
   </td>
  </tr>
  <tr class="data2" data-days="738651">
   <td class="left" nowrap="nowrap">
    <a class="data-link" href="/ci/content/player/529436.html">
     KS Bharat
    </a>
   </td>
   <td class="padAst" nowrap="nowrap">
    2
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td nowrap="nowrap">
    -
   </td>
   <td class="padDp2" nowrap="nowrap">
    -
   </td>

In [4]:
info_rows = most_runs.find_all("tr")
for row in info_rows:
    print (row.prettify())

<tr class="head">
 <th class="left" nowrap="nowrap" title="player name">
  Player
 </th>
 <th class="padAst" nowrap="nowrap" title="matches played">
  Mat
 </th>
 <th nowrap="nowrap" title="innings bowled">
  Inns
 </th>
 <th nowrap="nowrap" title="overs bowled">
  Overs
 </th>
 <th nowrap="nowrap" title="maidens earned">
  Mdns
 </th>
 <th nowrap="nowrap" title="runs conceded">
  Runs
 </th>
 <th nowrap="nowrap" title="wickets taken">
  Wkts
 </th>
 <th nowrap="nowrap" title="best innings bowling">
  BBI
 </th>
 <th nowrap="nowrap" title="bowling average">
  Ave
 </th>
 <th nowrap="nowrap" title="economy rate">
  Econ
 </th>
 <th nowrap="nowrap" title="bowling strike rate">
  SR
 </th>
 <th nowrap="nowrap" title="four wkts in an inns">
  4
 </th>
 <th nowrap="nowrap" title="five wkts in an inns">
  5
 </th>
 <th nowrap="nowrap" title="catches taken">
  Ct
 </th>
 <th nowrap="nowrap" title="stumpings made">
  St
 </th>
</tr>

<tr class="data2" data-days="738612">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/360911.html">
   VR Aaron
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  5.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  52
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  2/45
 </td>
 <td nowrap="nowrap">
  26.00
 </td>
 <td nowrap="nowrap">
  10.40
 </td>
 <td nowrap="nowrap">
  15.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738612">
 <td colspan="15">
  (Gujarat Titans)
 </td>
</tr>

<tr class="data2" data-days="738645">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/398666.html">
   SA Abbott
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  4.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  47
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1/47
 </td>
 <td nowrap="nowrap">
  47.00
 </td>
 <td nowrap="nowrap">
  11.75
 </td>
 <td nowrap="nowrap">
  24.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738645">
 <td colspan="15">
  (Sunrisers Hyderabad)
 </td>
</tr>

<tr class="data2" data-days="738614">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1175485.html">
   Abdul Samad
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  8
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  8.00
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738614">
 <td colspan="15">
  (Sunrisers Hyderabad)
 </td>
</tr>

<tr class="data2" data-days="738662">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1070183.html">
   Abhishek Sharma
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  14
 </td>
 <td nowrap="nowrap">
  3
 </td>
 <td nowrap="nowrap">
  4.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  38
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  9.50
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738662">
 <td colspan="15">
  (Sunrisers Hyderabad)
 </td>
</tr>

<tr class="data2" data-days="738662">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/398438.html">
   MA Agarwal
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  13
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738662">
 <td colspan="15">
  (Punjab Kings)
 </td>
</tr>

<tr class="data2" data-days="738661">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/942645.html">
   KK Ahmed
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  39.1
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  315
 </td>
 <td nowrap="nowrap">
  16
 </td>
 <td nowrap="nowrap">
  3/25
 </td>
 <td nowrap="nowrap">
  19.68
 </td>
 <td nowrap="nowrap">
  8.04
 </td>
 <td nowrap="nowrap">
  14.6
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738661">
 <td colspan="15">
  (Delhi Capitals)
 </td>
</tr>

<tr class="data2" data-days="738622">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1176959.html">
   Akash Deep
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  18.5
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  205
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  3/45
 </td>
 <td nowrap="nowrap">
  41.00
 </td>
 <td nowrap="nowrap">
  10.88
 </td>
 <td nowrap="nowrap">
  22.6
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738622">
 <td colspan="15">
  (Royal Challengers Bangalore)
 </td>
</tr>

<tr class="data2" data-days="738660">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/8917.html">
   MM Ali
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  23.5
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  158
 </td>
 <td nowrap="nowrap">
  8
 </td>
 <td nowrap="nowrap">
  3/13
 </td>
 <td nowrap="nowrap">
  19.75
 </td>
 <td nowrap="nowrap">
  6.62
 </td>
 <td nowrap="nowrap">
  17.8
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738660">
 <td colspan="15">
  (Chennai Super Kings)
 </td>
</tr>

<tr class="data2" data-days="738626">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/670013.html">
   FA Allen
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  4.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  46
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1/46
 </td>
 <td nowrap="nowrap">
  46.00
 </td>
 <td nowrap="nowrap">
  11.50
 </td>
 <td nowrap="nowrap">
  24.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738626">
 <td colspan="15">
  (Mumbai Indians)
 </td>
</tr>

<tr class="data2" data-days="738625">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1254269.html">
   Aman Hakim Khan
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  1.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  13
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  13.00
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738625">
 <td colspan="15">
  (Kolkata Knight Riders)
 </td>
</tr>

<tr class="data2" data-days="738612">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/851261.html">
   Anmolpreet Singh
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738612">
 <td colspan="15">
  (Mumbai Indians)
 </td>
</tr>

<tr class="data2" data-days="738633">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1123073.html">
   Anuj Rawat
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  8
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738633">
 <td colspan="15">
  (Royal Challengers Bangalore)
 </td>
</tr>

<tr class="data2" data-days="738630">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1209292.html">
   VG Arora
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  17.5
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  164
 </td>
 <td nowrap="nowrap">
  3
 </td>
 <td nowrap="nowrap">
  2/21
 </td>
 <td nowrap="nowrap">
  54.66
 </td>
 <td nowrap="nowrap">
  9.19
 </td>
 <td nowrap="nowrap">
  35.6
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738630">
 <td colspan="15">
  (Punjab Kings)
 </td>
</tr>

<tr class="data2" data-days="738662">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1125976.html">
   Arshdeep Singh
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  14
 </td>
 <td nowrap="nowrap">
  14
 </td>
 <td nowrap="nowrap">
  50.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  385
 </td>
 <td nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  3/37
 </td>
 <td nowrap="nowrap">
  38.50
 </td>
 <td nowrap="nowrap">
  7.70
 </td>
 <td nowrap="nowrap">
  30.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  4
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738662">
 <td colspan="15">
  (Punjab Kings)
 </td>
</tr>

<tr class="data2" data-days="738649">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/528067.html">
   M Ashwin
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  8
 </td>
 <td nowrap="nowrap">
  8
 </td>
 <td nowrap="nowrap">
  29.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  228
 </td>
 <td nowrap="nowrap">
  9
 </td>
 <td nowrap="nowrap">
  2/14
 </td>
 <td nowrap="nowrap">
  25.33
 </td>
 <td nowrap="nowrap">
  7.86
 </td>
 <td nowrap="nowrap">
  19.3
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738649">
 <td colspan="15">
  (Mumbai Indians)
 </td>
</tr>

<tr class="data2" data-days="738669">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/26421.html">
   R Ashwin
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  17
 </td>
 <td nowrap="nowrap">
  17
 </td>
 <td nowrap="nowrap">
  67.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  503
 </td>
 <td nowrap="nowrap">
  12
 </td>
 <td nowrap="nowrap">
  3/17
 </td>
 <td nowrap="nowrap">
  41.91
 </td>
 <td nowrap="nowrap">
  7.50
 </td>
 <td nowrap="nowrap">
  33.5
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738669">
 <td colspan="15">
  (Rajasthan Royals)
 </td>
</tr>

<tr class="data2" data-days="738665">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/694211.html">
   Avesh Khan
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  13
 </td>
 <td nowrap="nowrap">
  13
 </td>
 <td nowrap="nowrap">
  47.4
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  416
 </td>
 <td nowrap="nowrap">
  18
 </td>
 <td nowrap="nowrap">
  4/24
 </td>
 <td nowrap="nowrap">
  23.11
 </td>
 <td nowrap="nowrap">
  8.72
 </td>
 <td nowrap="nowrap">
  15.8
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738665">
 <td colspan="15">
  (Lucknow Super Giants)
 </td>
</tr>

<tr class="data2" data-days="738655">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1151270.html">
   A Badoni
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  13
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  2.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  11
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  1/5
 </td>
 <td nowrap="nowrap">
  5.50
 </td>
 <td nowrap="nowrap">
  5.50
 </td>
 <td nowrap="nowrap">
  6.0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  9
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738655">
 <td colspan="15">
  (Lucknow Super Giants)
 </td>
</tr>

<tr class="data2" data-days="738662">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/297433.html">
   JM Bairstow
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  11
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738662">
 <td colspan="15">
  (Punjab Kings)
 </td>
</tr>

<tr class="data2" data-days="738623">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/732291.html">
   Basil Thampi
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  16.0
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  152
 </td>
 <td nowrap="nowrap">
  5
 </td>
 <td nowrap="nowrap">
  3/35
 </td>
 <td nowrap="nowrap">
  30.40
 </td>
 <td nowrap="nowrap">
  9.50
 </td>
 <td nowrap="nowrap">
  19.2
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738623">
 <td colspan="15">
  (Mumbai Indians)
 </td>
</tr>

<tr class="data2" data-days="738611">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/1292502.html">
   RA Bawa
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738611">
 <td colspan="15">
  (Punjab Kings)
 </td>
</tr>

<tr class="data2" data-days="738651">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/529436.html">
   KS Bharat
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738651">
 <td colspan="15">
  (Delhi Capitals)
 </td>
</tr>

<tr class="data2" data-days="738658">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/297628.html">
   SW Billings
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  8
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp2" nowrap="nowrap">
  -
 </td>
 <td class="padDp1" nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  -
 </td>
 <td nowrap="nowrap">
  6
 </td>
 <td nowrap="nowrap">
  1
 </td>
</tr>

<tr class="note" data-days="738658">
 <td colspan="15">
  (Kolkata Knight Riders)
 </td>
</tr>

<tr class="data2" data-days="738669">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/277912.html">
   TA Boult
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  16
 </td>
 <td nowrap="nowrap">
  16
 </td>
 <td nowrap="nowrap">
  62.0
 </td>
 <td nowrap="nowrap">
  3
 </td>
 <td nowrap="nowrap">
  492
 </td>
 <td nowrap="nowrap">
  16
 </td>
 <td nowrap="nowrap">
  2/18
 </td>
 <td nowrap="nowrap">
  30.75
 </td>
 <td nowrap="nowrap">
  7.93
 </td>
 <td nowrap="nowrap">
  23.2
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  2
 </td>
 <td nowrap="nowrap">
  0
 </td>
</tr>

<tr class="note" data-days="738669">
 <td colspan="15">
  (Rajasthan Royals)
 </td>
</tr>

<tr class="data2" data-days="738652">
 <td class="left" nowrap="nowrap">
  <a class="data-link" href="/ci/content/player/51439.html">
   DJ Bravo
  </a>
 </td>
 <td class="padAst" nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  10
 </td>
 <td nowrap="nowrap">
  34.2
 </td>
 <td nowrap="nowrap">
  1
 </td>
 <td nowrap="nowrap">
  299
 </td>
 <td nowrap="nowrap">
  16
 </td>
 <td nowrap="nowrap">
  3/20
 </td>
 <td nowrap="nowrap">
  18.68
 </td>
 <td nowrap="nowrap">
  8.70
 </td>
 <td nowrap="nowrap">
  12.8
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  0
 </td>
 <td nowrap="nowrap">
  3
 </td>

In [5]:
import pandas as pd

In [6]:
info = []
header = []
i = 0
for index,row in enumerate(info_rows):
    if index == 0:
        header= row.get_text().split('\n')[1:-1]
        print(row)
        df1 = pd.DataFrame(index = range(0,340), columns = header)
    if index != 0:
        info.append(row.get_text().split('\n')[1:-1])
        print(row)
        #names[1:]= row.find('td').get_text()
        if index % 2 == 0:
            df1.loc[i]= info[i]
            i+=2
#for i <= len(info):
    
print(header)
print(info)
print(index)

<tr class="head">
<th class="left" nowrap="nowrap" title="player name">Player</th>
<th class="padAst" nowrap="nowrap" title="matches played">Mat</th>
<th nowrap="nowrap" title="innings bowled">Inns</th>
<th nowrap="nowrap" title="overs bowled">Overs</th>
<th nowrap="nowrap" title="maidens earned">Mdns</th>
<th nowrap="nowrap" title="runs conceded">Runs</th>
<th nowrap="nowrap" title="wickets taken">Wkts</th>
<th nowrap="nowrap" title="best innings bowling">BBI</th>
<th nowrap="nowrap" title="bowling average">Ave</th>
<th nowrap="nowrap" title="economy rate">Econ</th>
<th nowrap="nowrap" title="bowling strike rate">SR</th>
<th nowrap="nowrap" title="four wkts in an inns">4</th>
<th nowrap="nowrap" title="five wkts in an inns">5</th>
<th nowrap="nowrap" title="catches taken">Ct</th>
<th nowrap="nowrap" title="stumpings made">St</th>
</tr>
<tr class="data2" data-days="738612">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/360911.html">VR Aaron</a></td>
<td class="padAst" nowrap="nowrap">2</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">5.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">52</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">2/45</td>
<td nowrap="nowrap">26.00</td>
<td nowrap="nowrap">10.40</td>
<td nowrap="nowrap">15.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738612">
<td colspan="15">(Gujarat Titans)</td>
</tr>
<tr class="data2" data-days="738645">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/398666.html">SA Abbott</a></td>
<td class="padAst" nowrap="nowrap">1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">4.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">47</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1/47</td>
<td nowrap="nowrap">47.00</td>
<td nowrap="nowrap">11.75</td>
<td nowrap="nowrap">24.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738645">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738614">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1175485.html">Abdul Samad</a></td>
<td class="padAst" nowrap="nowrap">2</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">8</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td nowrap="nowrap">8.00</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738614">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1070183.html">Abhishek Sharma</a></td>
<td class="padAst" nowrap="nowrap">14</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">4.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">38</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td nowrap="nowrap">9.50</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/398438.html">MA Agarwal</a></td>
<td class="padAst" nowrap="nowrap">13</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Punjab Kings)</td>
</tr>
<tr class="data2" data-days="738661">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/942645.html">KK Ahmed</a></td>
<td class="padAst" nowrap="nowrap">10</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">39.1</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">315</td>
<td nowrap="nowrap">16</td>
<td nowrap="nowrap">3/25</td>
<td nowrap="nowrap">19.68</td>
<td nowrap="nowrap">8.04</td>
<td nowrap="nowrap">14.6</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738661">
<td colspan="15">(Delhi Capitals)</td>
</tr>
<tr class="data2" data-days="738622">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1176959.html">Akash Deep</a></td>
<td class="padAst" nowrap="nowrap">5</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">18.5</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">205</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">3/45</td>
<td nowrap="nowrap">41.00</td>
<td nowrap="nowrap">10.88</td>
<td nowrap="nowrap">22.6</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738622">
<td colspan="15">(Royal Challengers Bangalore)</td>
</tr>
<tr class="data2" data-days="738660">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/8917.html">MM Ali</a></td>
<td class="padAst" nowrap="nowrap">10</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">23.5</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">158</td>
<td nowrap="nowrap">8</td>
<td nowrap="nowrap">3/13</td>
<td nowrap="nowrap">19.75</td>
<td nowrap="nowrap">6.62</td>
<td nowrap="nowrap">17.8</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738660">
<td colspan="15">(Chennai Super Kings)</td>
</tr>
<tr class="data2" data-days="738626">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/670013.html">FA Allen</a></td>
<td class="padAst" nowrap="nowrap">1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">4.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">46</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1/46</td>
<td nowrap="nowrap">46.00</td>
<td nowrap="nowrap">11.50</td>
<td nowrap="nowrap">24.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738626">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738625">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1254269.html">Aman Hakim Khan</a></td>
<td class="padAst" nowrap="nowrap">1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">13</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td nowrap="nowrap">13.00</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738625">
<td colspan="15">(Kolkata Knight Riders)</td>
</tr>
<tr class="data2" data-days="738612">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/851261.html">Anmolpreet Singh</a></td>
<td class="padAst" nowrap="nowrap">2</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738612">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738633">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1123073.html">Anuj Rawat</a></td>
<td class="padAst" nowrap="nowrap">8</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738633">
<td colspan="15">(Royal Challengers Bangalore)</td>
</tr>
<tr class="data2" data-days="738630">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1209292.html">VG Arora</a></td>
<td class="padAst" nowrap="nowrap">5</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">17.5</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">164</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">2/21</td>
<td nowrap="nowrap">54.66</td>
<td nowrap="nowrap">9.19</td>
<td nowrap="nowrap">35.6</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738630">
<td colspan="15">(Punjab Kings)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1125976.html">Arshdeep Singh</a></td>
<td class="padAst" nowrap="nowrap">14</td>
<td nowrap="nowrap">14</td>
<td nowrap="nowrap">50.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">385</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">3/37</td>
<td nowrap="nowrap">38.50</td>
<td nowrap="nowrap">7.70</td>
<td nowrap="nowrap">30.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">4</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Punjab Kings)</td>
</tr>
<tr class="data2" data-days="738649">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/528067.html">M Ashwin</a></td>
<td class="padAst" nowrap="nowrap">8</td>
<td nowrap="nowrap">8</td>
<td nowrap="nowrap">29.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">228</td>
<td nowrap="nowrap">9</td>
<td nowrap="nowrap">2/14</td>
<td nowrap="nowrap">25.33</td>
<td nowrap="nowrap">7.86</td>
<td nowrap="nowrap">19.3</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738649">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738669">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/26421.html">R Ashwin</a></td>
<td class="padAst" nowrap="nowrap">17</td>
<td nowrap="nowrap">17</td>
<td nowrap="nowrap">67.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">503</td>
<td nowrap="nowrap">12</td>
<td nowrap="nowrap">3/17</td>
<td nowrap="nowrap">41.91</td>
<td nowrap="nowrap">7.50</td>
<td nowrap="nowrap">33.5</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738669">
<td colspan="15">(Rajasthan Royals)</td>
</tr>
<tr class="data2" data-days="738665">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/694211.html">Avesh Khan</a></td>
<td class="padAst" nowrap="nowrap">13</td>
<td nowrap="nowrap">13</td>
<td nowrap="nowrap">47.4</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">416</td>
<td nowrap="nowrap">18</td>
<td nowrap="nowrap">4/24</td>
<td nowrap="nowrap">23.11</td>
<td nowrap="nowrap">8.72</td>
<td nowrap="nowrap">15.8</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738665">
<td colspan="15">(Lucknow Super Giants)</td>
</tr>
<tr class="data2" data-days="738655">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1151270.html">A Badoni</a></td>
<td class="padAst" nowrap="nowrap">13</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">2.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">11</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">1/5</td>
<td nowrap="nowrap">5.50</td>
<td nowrap="nowrap">5.50</td>
<td nowrap="nowrap">6.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">9</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738655">
<td colspan="15">(Lucknow Super Giants)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/297433.html">JM Bairstow</a></td>
<td class="padAst" nowrap="nowrap">11</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Punjab Kings)</td>
</tr>
<tr class="data2" data-days="738623">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/732291.html">Basil Thampi</a></td>
<td class="padAst" nowrap="nowrap">5</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">16.0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">152</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">3/35</td>
<td nowrap="nowrap">30.40</td>
<td nowrap="nowrap">9.50</td>
<td nowrap="nowrap">19.2</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738623">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738611">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1292502.html">RA Bawa</a></td>
<td class="padAst" nowrap="nowrap">2</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738611">
<td colspan="15">(Punjab Kings)</td>
</tr>
<tr class="data2" data-days="738651">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/529436.html">KS Bharat</a></td>
<td class="padAst" nowrap="nowrap">2</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738651">
<td colspan="15">(Delhi Capitals)</td>
</tr>
<tr class="data2" data-days="738658">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/297628.html">SW Billings</a></td>
<td class="padAst" nowrap="nowrap">8</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">1</td>
</tr>
<tr class="note" data-days="738658">
<td colspan="15">(Kolkata Knight Riders)</td>
</tr>
<tr class="data2" data-days="738669">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/277912.html">TA Boult</a></td>
<td class="padAst" nowrap="nowrap">16</td>
<td nowrap="nowrap">16</td>
<td nowrap="nowrap">62.0</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">492</td>
<td nowrap="nowrap">16</td>
<td nowrap="nowrap">2/18</td>
<td nowrap="nowrap">30.75</td>
<td nowrap="nowrap">7.93</td>
<td nowrap="nowrap">23.2</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738669">
<td colspan="15">(Rajasthan Royals)</td>
</tr>
<tr class="data2" data-days="738652">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/51439.html">DJ Bravo</a></td>
<td class="padAst" nowrap="nowrap">10</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">34.2</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">299</td>
<td nowrap="nowrap">16</td>
<td nowrap="nowrap">3/20</td>
<td nowrap="nowrap">18.68</td>
<td nowrap="nowrap">8.70</td>
<td nowrap="nowrap">12.8</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738652">
<td colspan="15">(Chennai Super Kings)</td>
</tr>
<tr class="data2" data-days="738661">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1070665.html">D Brevis</a></td>
<td class="padAst" nowrap="nowrap">7</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0.3</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">8</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1/8</td>
<td nowrap="nowrap">8.00</td>
<td nowrap="nowrap">16.00</td>
<td nowrap="nowrap">3.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738661">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738661">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/625383.html">JJ Bumrah</a></td>
<td class="padAst" nowrap="nowrap">14</td>
<td nowrap="nowrap">14</td>
<td nowrap="nowrap">53.2</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">383</td>
<td nowrap="nowrap">15</td>
<td nowrap="nowrap">5/10</td>
<td nowrap="nowrap">25.53</td>
<td nowrap="nowrap">7.18</td>
<td nowrap="nowrap">21.3</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738661">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738669">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/308967.html">JC Buttler</a></td>
<td class="padAst" nowrap="nowrap">17</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">9</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738669">
<td colspan="15">(Rajasthan Royals)</td>
</tr>
<tr class="data2" data-days="738669">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/430246.html">YS Chahal</a></td>
<td class="padAst" nowrap="nowrap">17</td>
<td nowrap="nowrap">17</td>
<td nowrap="nowrap">68.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">527</td>
<td nowrap="nowrap">27</td>
<td nowrap="nowrap">5/40</td>
<td nowrap="nowrap">19.51</td>
<td nowrap="nowrap">7.75</td>
<td nowrap="nowrap">15.1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738669">

<tr class="data2" data-days="738661">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1170265.html">NT Tilak Varma</a></td>
<td class="padAst" nowrap="nowrap">14</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">2.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">13</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td nowrap="nowrap">6.50</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738661">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738658">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1081183.html">A Tomar</a></td>
<td class="padAst" nowrap="nowrap">1</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738658">
<td colspan="15">(Kolkata Knight Riders)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/446763.html">RA Tripathi</a></td>
<td class="padAst" nowrap="nowrap">14</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738617">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/459508.html">AJ Tye</a></td>
<td class="padAst" nowrap="nowrap">3</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">11.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">107</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">2/40</td>
<td nowrap="nowrap">53.50</td>
<td nowrap="nowrap">9.72</td>
<td nowrap="nowrap">33.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738617">
<td colspan="15">(Lucknow Super Giants)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1246528.html">Umran Malik</a></td>
<td class="padAst" nowrap="nowrap">14</td>
<td nowrap="nowrap">14</td>
<td nowrap="nowrap">49.1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">444</td>
<td nowrap="nowrap">22</td>
<td nowrap="nowrap">5/25</td>
<td nowrap="nowrap">20.18</td>
<td nowrap="nowrap">9.03</td>
<td nowrap="nowrap">13.4</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738634">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/390484.html">JD Unadkat</a></td>
<td class="padAst" nowrap="nowrap">5</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">20.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">190</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">2/32</td>
<td nowrap="nowrap">31.66</td>
<td nowrap="nowrap">9.50</td>
<td nowrap="nowrap">20.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738634">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738652">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/35582.html">RV Uthappa</a></td>
<td class="padAst" nowrap="nowrap">12</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738652">
<td colspan="15">(Chennai Super Kings)</td>
</tr>
<tr class="data2" data-days="738651">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/337790.html">HE van der Dussen</a></td>
<td class="padAst" nowrap="nowrap">3</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738651">
<td colspan="15">(Rajasthan Royals)</td>
</tr>
<tr class="data2" data-days="738658">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1108375.html">CV Varun</a></td>
<td class="padAst" nowrap="nowrap">11</td>
<td nowrap="nowrap">11</td>
<td nowrap="nowrap">39.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">332</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">1/22</td>
<td nowrap="nowrap">55.33</td>
<td nowrap="nowrap">8.51</td>
<td nowrap="nowrap">39.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738658">
<td colspan="15">(Kolkata Knight Riders)</td>
</tr>
<tr class="data2" data-days="738665">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/532856.html">M Vohra</a></td>
<td class="padAst" nowrap="nowrap">2</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738665">
<td colspan="15">(Lucknow Super Giants)</td>
</tr>
<tr class="data2" data-days="738669">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/230193.html">MS Wade</a></td>
<td class="padAst" nowrap="nowrap">10</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">7</td>
<td nowrap="nowrap">1</td>
</tr>
<tr class="note" data-days="738669">
<td colspan="15">(Gujarat Titans)</td>
</tr>
<tr class="data2" data-days="738661">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/219889.html">DA Warner</a></td>
<td class="padAst" nowrap="nowrap">12</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738661">
<td colspan="15">(Delhi Capitals)</td>
</tr>
<tr class="data2" data-days="738662">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/719715.html">Washington Sundar</a></td>
<td class="padAst" nowrap="nowrap">9</td>
<td nowrap="nowrap">8</td>
<td nowrap="nowrap">28.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">239</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">2/21</td>
<td nowrap="nowrap">39.83</td>
<td nowrap="nowrap">8.53</td>
<td nowrap="nowrap">28.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738662">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738619">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/308251.html">DJ Willey</a></td>
<td class="padAst" nowrap="nowrap">4</td>
<td nowrap="nowrap">4</td>
<td nowrap="nowrap">11.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">72</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">1/29</td>
<td nowrap="nowrap">72.00</td>
<td nowrap="nowrap">6.54</td>
<td nowrap="nowrap">66.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738619">
<td colspan="15">(Royal Challengers Bangalore)</td>
</tr>
<tr class="data2" data-days="738657">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/277906.html">KS Williamson</a></td>
<td class="padAst" nowrap="nowrap">13</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">10</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738657">
<td colspan="15">(Sunrisers Hyderabad)</td>
</tr>
<tr class="data2" data-days="738656">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/930189.html">Lalit Yadav</a></td>
<td class="padAst" nowrap="nowrap">12</td>
<td nowrap="nowrap">8</td>
<td nowrap="nowrap">18.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">150</td>
<td nowrap="nowrap">4</td>
<td nowrap="nowrap">2/11</td>
<td nowrap="nowrap">37.50</td>
<td nowrap="nowrap">8.33</td>
<td nowrap="nowrap">27.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">6</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738656">
<td colspan="15">(Delhi Capitals)</td>
</tr>
<tr class="data2" data-days="738646">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/446507.html">SA Yadav</a></td>
<td class="padAst" nowrap="nowrap">8</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp2" nowrap="nowrap">-</td>
<td class="padDp1" nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">-</td>
<td nowrap="nowrap">3</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738646">
<td colspan="15">(Mumbai Indians)</td>
</tr>
<tr class="data2" data-days="738658">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/376116.html">UT Yadav</a></td>
<td class="padAst" nowrap="nowrap">12</td>
<td nowrap="nowrap">12</td>
<td nowrap="nowrap">48.0</td>
<td nowrap="nowrap">2</td>
<td nowrap="nowrap">339</td>
<td nowrap="nowrap">16</td>
<td nowrap="nowrap">4/23</td>
<td nowrap="nowrap">21.18</td>
<td nowrap="nowrap">7.06</td>
<td nowrap="nowrap">18.0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">5</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738658">
<td colspan="15">(Kolkata Knight Riders)</td>
</tr>
<tr class="data2" data-days="738669">
<td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/player/1159720.html">Yash Dayal</a></td>
<td class="padAst" nowrap="nowrap">9</td>
<td nowrap="nowrap">9</td>
<td nowrap="nowrap">32.0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">296</td>
<td nowrap="nowrap">11</td>
<td nowrap="nowrap">3/40</td>
<td nowrap="nowrap">26.90</td>
<td nowrap="nowrap">9.25</td>
<td nowrap="nowrap">17.4</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">0</td>
<td nowrap="nowrap">1</td>
<td nowrap="nowrap">0</td>
</tr>
<tr class="note" data-days="738669">
<td colspan="15">(Gujarat Titans)</td>
</tr>
['Player', 'Mat', 'Inns', 'Overs', 'Mdns', 'Runs', 'Wkts', 'BBI', 'Ave', 'Econ', 'SR', '4', '5', 'Ct', 'St']

In [61]:
df1

,Player,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5,Ct,St
0,VR Aaron,2,2,5.0,0,52,2,2/45,26.00,10.40,15.0,0,0,0,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SA Abbott,1,1,4.0,0,47,1,1/47,47.00,11.75,24.0,0,0,1,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abdul Samad,2,1,1.0,0,8,0,-,-,8.00,-,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,KS Williamson,13,-,-,-,-,-,-,-,-,-,-,-,10,0
372,Lalit Yadav,12,8,18.0,0,150,4,2/11,37.50,8.33,27.0,0,0,6,0
374,SA Yadav,8,-,-,-,-,-,-,-,-,-,-,-,3,0
376,UT Yadav,12,12,48.0,2,339,16,4/23,21.18,7.06,18.0,1,0,5,0
378,Yash Dayal,9,9,32.0,0,296,11,3/40,26.90,9.25,17.4,0,0,1,0

In [62]:
print(len(header))
print(type(info[1][0]))

15
<class 'str'>

In [63]:
df_bowling = df1.dropna()

In [64]:
df_bowling= df_bowling.reset_index(drop=True)

In [65]:
i=0
team = []
while i < len(info):
    if i % 2 != 0:
        team.append(info[i][0][1:-1])
    i+=1

df_bowling.insert(1,'Team',team)

In [66]:
df_bowling['Wkts'] = df_bowling['Wkts'].replace(np.nan ,0, regex = True)
df_bowling['Wkts'] = df_bowling['Wkts'].replace( '-',0, regex = True)

In [67]:
df_bowling['Econ'] = df_bowling['Econ'].replace( '-',0, regex = True)

In [68]:
for col in df_bowling.columns:
    if col not in ['BBI', 'Player','Team']:
        if df_bowling[col].dtype!= float:
            try:
                df_bowling[col] = df_bowling[col].astype('float32')
            except Exception as e:
                df_bowling[col] = df_bowling[col].replace( '-',0, regex = True)
                df_bowling[col] = df_bowling[col].astype('float32')

In [69]:
df_bowling.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  190 non-null    object
 1   Team    190 non-null    object
 2   Mat     190 non-null    float32
 3   Inns    190 non-null    float32
 4   Overs   190 non-null    float32
 5   Mdns    190 non-null    float32
 6   Runs    190 non-null    float32
 7   Wkts    190 non-null    float32
 8   BBI     190 non-null    object
 9   Ave     190 non-null    float32
 10  Econ    190 non-null    float32
 11  SR      190 non-null    float32
 12  4       190 non-null    float32
 13  5       190 non-null    float32
 14  Ct      190 non-null    float32
 15  St      190 non-null    float32
dtypes: float32(13), object(3)
memory usage: 14.2+ KB

In [70]:
df_bowling.sort_values(by='Wkts', ascending=False)

,Player,Team,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5,Ct,St
28,YS Chahal,Rajasthan Royals,17.0,17.0,68.000000,0.0,527.0,27.0,5/40,19.510000,7.75,15.1,1.0,1.0,0.0,0.0
37,PWH de Silva,Royal Challengers Bangalore,16.0,16.0,57.000000,1.0,430.0,26.0,5/18,16.530001,7.54,13.1,1.0,1.0,3.0,0.0
122,K Rabada,Punjab Kings,13.0,13.0,48.000000,0.0,406.0,23.0,4/33,17.650000,8.45,12.5,2.0,0.0,2.0,0.0
175,Umran Malik,Sunrisers Hyderabad,14.0,14.0,49.099998,1.0,444.0,22.0,5/25,20.180000,9.03,13.4,1.0,1.0,5.0,0.0
74,Kuldeep Yadav,Delhi Capitals,14.0,14.0,49.400002,0.0,419.0,21.0,4/14,19.950001,8.43,14.1,2.0,0.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,YBK Jaiswal,Rajasthan Royals,10.0,1.0,0.100000,0.0,6.0,0.0,-,0.000000,36.00,0.0,0.0,0.0,2.0,0.0
68,KD Karthik,Royal Challengers Bangalore,16.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.0,0.0,0.0,10.0,2.0
119,SS Prabhudessai,Royal Challengers Bangalore,5.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.0,0.0,0.0,3.0,0.0
118,Prabhsimran Singh,Punjab Kings,1.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
32,NM Coulter-Nile,Rajasthan Royals,1.0,1.0,3.000000,0.0,48.0,0.0,-,0.000000,16.00,0.0,0.0,0.0,0.0,0.0

In [71]:
df_bowling.head(50)

,Player,Team,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5,Ct,St
0,VR Aaron,Gujarat Titans,2.0,2.0,5.000000,0.0,52.0,2.0,2/45,26.000000,10.40,15.000000,0.0,0.0,0.0,0.0
1,SA Abbott,Sunrisers Hyderabad,1.0,1.0,4.000000,0.0,47.0,1.0,1/47,47.000000,11.75,24.000000,0.0,0.0,1.0,0.0
2,Abdul Samad,Sunrisers Hyderabad,2.0,1.0,1.000000,0.0,8.0,0.0,-,0.000000,8.00,0.000000,0.0,0.0,1.0,0.0
3,Abhishek Sharma,Sunrisers Hyderabad,14.0,3.0,4.000000,0.0,38.0,0.0,-,0.000000,9.50,0.000000,0.0,0.0,1.0,0.0
4,MA Agarwal,Punjab Kings,13.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,10.0,0.0
5,KK Ahmed,Delhi Capitals,10.0,10.0,39.099998,0.0,315.0,16.0,3/25,19.680000,8.04,14.600000,0.0,0.0,0.0,0.0
6,Akash Deep,Royal Challengers Bangalore,5.0,5.0,18.500000,1.0,205.0,5.0,3/45,41.000000,10.88,22.600000,0.0,0.0,2.0,0.0
7,MM Ali,Chennai Super Kings,10.0,10.0,23.500000,0.0,158.0,8.0,3/13,19.750000,6.62,17.799999,0.0,0.0,5.0,0.0
8,FA Allen,Mumbai Indians,1.0,1.0,4.000000,0.0,46.0,1.0,1/46,46.000000,11.50,24.000000,0.0,0.0,0.0,0.0
9,Aman Hakim Khan,Kolkata Knight Riders,1.0,1.0,1.000000,0.0,13.0,0.0,-,0.000000,13.00,0.000000,0.0,0.0,0.0,0.0
10,Anmolpreet Singh,Mumbai Indians,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
11,Anuj Rawat,Royal Challengers Bangalore,8.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,5.0,0.0
12,VG Arora,Punjab Kings,5.0,5.0,17.500000,0.0,164.0,3.0,2/21,54.660000,9.19,35.599998,0.0,0.0,1.0,0.0
13,Arshdeep Singh,Punjab Kings,14.0,14.0,50.000000,0.0,385.0,10.0,3/37,38.500000,7.70,30.000000,0.0,0.0,4.0,0.0
14,M Ashwin,Mumbai Indians,8.0,8.0,29.000000,0.0,228.0,9.0,2/14,25.330000,7.86,19.299999,0.0,0.0,0.0,0.0
15,R Ashwin,Rajasthan Royals,17.0,17.0,67.000000,0.0,503.0,12.0,3/17,41.910000,7.50,33.500000,0.0,0.0,5.0,0.0
16,Avesh Khan,Lucknow Super Giants,13.0,13.0,47.400002,1.0,416.0,18.0,4/24,23.110001,8.72,15.800000,1.0,0.0,2.0,0.0
17,A Badoni,Lucknow Super Giants,13.0,2.0,2.000000,0.0,11.0,2.0,1/5,5.500000,5.50,6.000000,0.0,0.0,9.0,0.0
18,JM Bairstow,Punjab Kings,11.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,2.0,0.0
19,Basil Thampi,Mumbai Indians,5.0,5.0,16.000000,1.0,152.0,5.0,3/35,30.400000,9.50,19.200001,0.0,0.0,1.0,0.0
20,RA Bawa,Punjab Kings,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
21,KS Bharat,Delhi Capitals,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
22,SW Billings,Kolkata Knight Riders,8.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,6.0,1.0
23,TA Boult,Rajasthan Royals,16.0,16.0,62.000000,3.0,492.0,16.0,2/18,30.750000,7.93,23.200001,0.0,0.0,2.0,0.0
24,DJ Bravo,Chennai Super Kings,10.0,10.0,34.200001,1.0,299.0,16.0,3/20,18.680000,8.70,12.800000,0.0,0.0,3.0,0.0
25,D Brevis,Mumbai Indians,7.0,1.0,0.300000,0.0,8.0,1.0,1/8,8.000000,16.00,3.000000,0.0,0.0,3.0,0.0
26,JJ Bumrah,Mumbai Indians,14.0,14.0,53.200001,2.0,383.0,15.0,5/10,25.530001,7.18,21.299999,0.0,1.0,2.0,0.0
27,JC Buttler,Rajasthan Royals,17.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,9.0,0.0
28,YS Chahal,Rajasthan Royals,17.0,17.0,68.000000,0.0,527.0,27.0,5/40,19.510000,7.75,15.100000,1.0,1.0,0.0,0.0
29,RD Chahar,Punjab Kings,13.0,13.0,46.400002,1.0,360.0,14.0,3/25,25.709999,7.71,20.000000,0.0,0.0,5.0,0.0
30,PVD Chameera,Lucknow Super Giants,12.0,12.0,44.000000,0.0,384.0,9.0,2/17,42.660000,8.72,29.299999,0.0,0.0,2.0,0.0
31,DP Conway,Chennai Super Kings,7.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,2.0,0.0
32,NM Coulter-Nile,Rajasthan Royals,1.0,1.0,3.000000,0.0,48.0,0.0,-,0.000000,16.00,0.000000,0.0,0.0,0.0,0.0
33,PJ Cummins,Kolkata Knight Riders,5.0,5.0,19.500000,0.0,212.0,7.0,3/22,30.280001,10.68,17.000000,0.0,0.0,1.0,0.0
34,TH David,Mumbai Indians,8.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,6.0,0.0
35,Q de Kock,Lucknow Super Giants,15.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,12.0,1.0
36,TU Deshpande,Chennai Super Kings,2.0,2.0,7.000000,0.0,63.0,1.0,1/40,63.000000,9.00,42.000000,0.0,0.0,1.0,0.0
37,PWH de Silva,Royal Challengers Bangalore,16.0,16.0,57.000000,1.0,430.0,26.0,5/18,16.530001,7.54,13.100000,1.0,1.0,3.0,0.0
38,R Dhawan,Punjab Kings,6.0,6.0,19.000000,0.0,156.0,6.0,2/36,26.000000,8.21,19.000000,0.0,0.0,2.0,0.0
39,S Dhawan,Punjab Kings,14.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,10.0,0.0
40,MS Dhoni,Chennai Super Kings,14.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,9.0,0.0
41,S Dube,Chennai Super Kings,11.0,2.0,2.000000,0.0,36.0,0.0,-,0.000000,18.00,0.000000,0.0,0.0,6.0,0.0
42,F du Plessis,Royal Challengers Bangalore,16.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,4.0,0.0
43,NT Ellis,Punjab Kings,2.0,2.0,6.000000,0.0,55.0,3.0,3/40,18.330000,9.16,12.000000,0.0,0.0,1.0,0.0
44,Fazalhaq Farooqi,Sunrisers Hyderabad,3.0,3.0,12.000000,0.0,110.0,2.0,2/32,55.000000,9.16,36.000000,0.0,0.0,0.0,0.0
45,LH Ferguson,Gujarat Titans,13.0,13.0,47.400002,0.0,427.0,12.0,4/28,35.580002,8.95,23.799999,1.0,0.0,2.0,0.0
46,AJ Finch,Kolkata Knight Riders,5.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,1.0,0.0
47,RD Gaikwad,Chennai Super Kings,14.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,4.0,0.0
48,PK Garg,Sunrisers Hyderabad,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,3.0,0.0
49,S Gopal,Sunrisers Hyderabad,1.0,1.0,3.000000,0.0,34.0,1.0,1/34,34.000000,11.33,18.000000,0.0,0.0,0.0,0.0

In [72]:
df_bowling.tail(50)

,Player,Team,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5,Ct,St
140,C Sakariya,Delhi Capitals,3.0,3.0,11.000000,0.0,84.0,3.0,2/23,28.000000,7.63,22.000000,0.0,0.0,2.0,0.0
141,DR Sams,Mumbai Indians,11.0,11.0,42.000000,0.0,370.0,13.0,4/30,28.459999,8.80,19.299999,1.0,0.0,7.0,0.0
142,SV Samson,Rajasthan Royals,17.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,14.0,2.0
143,Sandeep Sharma,Punjab Kings,5.0,5.0,20.000000,0.0,153.0,2.0,1/18,76.500000,7.65,60.000000,0.0,0.0,2.0,0.0
144,PJ Sangwan,Gujarat Titans,3.0,3.0,9.000000,0.0,65.0,3.0,2/19,21.660000,7.22,18.000000,0.0,0.0,1.0,0.0
145,R Sanjay Yadav,Mumbai Indians,1.0,1.0,2.000000,0.0,23.0,0.0,-,0.000000,11.50,0.000000,0.0,0.0,0.0,0.0
146,MJ Santner,Chennai Super Kings,6.0,6.0,19.000000,0.0,130.0,4.0,1/15,32.500000,6.84,28.500000,0.0,0.0,2.0,0.0
147,TL Seifert,Delhi Capitals,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,1.0,0.0
148,KR Sen,Rajasthan Royals,7.0,7.0,25.100000,0.0,237.0,8.0,4/20,29.620001,9.41,18.799999,1.0,0.0,3.0,0.0
149,M Shahrukh Khan,Punjab Kings,8.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,3.0,0.0
150,V Shankar,Gujarat Titans,4.0,2.0,1.300000,0.0,15.0,0.0,-,0.000000,10.00,0.000000,0.0,0.0,3.0,0.0
151,JM Sharma,Punjab Kings,12.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,9.0,2.0
152,KS Sharma,Lucknow Super Giants,1.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
153,RG Sharma,Mumbai Indians,14.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,7.0,0.0
154,Shashank Singh,Sunrisers Hyderabad,10.0,2.0,2.000000,0.0,20.0,0.0,-,0.000000,10.00,0.000000,0.0,0.0,3.0,0.0
155,PP Shaw,Delhi Capitals,10.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,4.0,0.0
156,R Shepherd,Sunrisers Hyderabad,3.0,3.0,9.000000,0.0,98.0,3.0,2/42,32.660000,10.88,18.000000,0.0,0.0,0.0,0.0
157,Shivam Mavi,Kolkata Knight Riders,6.0,6.0,22.000000,0.0,227.0,5.0,1/33,45.400002,10.31,26.400000,0.0,0.0,4.0,0.0
158,HR Shokeen,Mumbai Indians,5.0,5.0,15.000000,0.0,127.0,2.0,2/47,63.500000,8.46,45.000000,0.0,0.0,2.0,0.0
159,Shubman Gill,Gujarat Titans,16.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,7.0,0.0
160,Simarjeet Singh,Chennai Super Kings,6.0,6.0,18.000000,0.0,138.0,4.0,2/27,34.500000,7.66,27.000000,0.0,0.0,1.0,0.0
161,RK Singh,Kolkata Knight Riders,7.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,8.0,0.0
162,OF Smith,Punjab Kings,6.0,6.0,15.000000,0.0,178.0,6.0,4/30,29.660000,11.86,15.000000,1.0,0.0,2.0,0.0
163,PH Solanki,Chennai Super Kings,2.0,2.0,6.000000,0.0,38.0,2.0,2/20,19.000000,6.33,18.000000,0.0,0.0,0.0,0.0
164,TG Southee,Kolkata Knight Riders,9.0,9.0,35.000000,0.0,275.0,14.0,3/20,19.639999,7.85,15.000000,0.0,0.0,4.0,0.0
165,MP Stoinis,Lucknow Super Giants,11.0,5.0,7.000000,0.0,79.0,4.0,3/23,19.750000,11.28,10.500000,0.0,0.0,4.0,0.0
166,T Stubbs,Mumbai Indians,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
167,J Suchith,Sunrisers Hyderabad,5.0,5.0,18.000000,0.0,140.0,7.0,2/12,20.000000,7.77,15.400000,0.0,0.0,1.0,0.0
168,R Tewatia,Gujarat Titans,16.0,5.0,6.000000,0.0,76.0,0.0,-,0.000000,12.66,0.000000,0.0,0.0,5.0,0.0
169,SN Thakur,Delhi Capitals,14.0,14.0,48.200001,1.0,473.0,15.0,4/36,31.530001,9.78,19.299999,1.0,0.0,7.0,0.0
170,M Theekshana,Chennai Super Kings,9.0,9.0,35.000000,0.0,261.0,12.0,4/33,21.750000,7.45,17.500000,1.0,0.0,0.0,0.0
171,NT Tilak Varma,Mumbai Indians,14.0,2.0,2.000000,0.0,13.0,0.0,-,0.000000,6.50,0.000000,0.0,0.0,10.0,0.0
172,A Tomar,Kolkata Knight Riders,1.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
173,RA Tripathi,Sunrisers Hyderabad,14.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,6.0,0.0
174,AJ Tye,Lucknow Super Giants,3.0,3.0,11.000000,0.0,107.0,2.0,2/40,53.500000,9.72,33.000000,0.0,0.0,1.0,0.0
175,Umran Malik,Sunrisers Hyderabad,14.0,14.0,49.099998,1.0,444.0,22.0,5/25,20.180000,9.03,13.400000,1.0,1.0,5.0,0.0
176,JD Unadkat,Mumbai Indians,5.0,5.0,20.000000,0.0,190.0,6.0,2/32,31.660000,9.50,20.000000,0.0,0.0,1.0,0.0
177,RV Uthappa,Chennai Super Kings,12.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,5.0,0.0
178,HE van der Dussen,Rajasthan Royals,3.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
179,CV Varun,Kolkata Knight Riders,11.0,11.0,39.000000,0.0,332.0,6.0,1/22,55.330002,8.51,39.000000,0.0,0.0,2.0,0.0
180,M Vohra,Lucknow Super Giants,2.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0
181,MS Wade,Gujarat Titans,10.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,7.0,1.0
182,DA Warner,Delhi Capitals,12.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,6.0,0.0
183,Washington Sundar,Sunrisers Hyderabad,9.0,8.0,28.000000,0.0,239.0,6.0,2/21,39.830002,8.53,28.000000,0.0,0.0,1.0,0.0
184,DJ Willey,Royal Challengers Bangalore,4.0,4.0,11.000000,0.0,72.0,1.0,1/29,72.000000,6.54,66.000000,0.0,0.0,1.0,0.0
185,KS Williamson,Sunrisers Hyderabad,13.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,10.0,0.0
186,Lalit Yadav,Delhi Capitals,12.0,8.0,18.000000,0.0,150.0,4.0,2/11,37.500000,8.33,27.000000,0.0,0.0,6.0,0.0
187,SA Yadav,Mumbai Indians,8.0,0.0,0.000000,0.0,0.0,0.0,-,0.000000,0.00,0.000000,0.0,0.0,3.0,0.0
188,UT Yadav,Kolkata Knight Riders,12.0,12.0,48.000000,2.0,339.0,16.0,4/23,21.180000,7.06,18.000000,1.0,0.0,5.0,0.0
189,Yash Dayal,Gujarat Titans,9.0,9.0,32.000000,0.0,296.0,11.0,3/40,26.900000,9.25,17.400000,0.0,0.0,1.0,0.0

In [73]:
df_bowling.describe()

,Mat,Inns,Overs,Mdns,Runs,Wkts,Ave,Econ,SR,4,5,Ct,St
count,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000
mean,8.568421,4.510526,14.998949,0.147368,126.236839,4.468421,18.261049,6.204000,12.581580,0.110526,0.021053,3.368421,0.094737
std,5.145813,5.163709,18.987980,0.492664,154.122162,6.296598,20.519480,5.205664,14.147932,0.346402,0.143939,3.236867,0.450131
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,8.000000,2.000000,5.050000,0.000000,52.000000,1.000000,18.505000,7.660000,12.650000,0.000000,0.000000,2.000000,0.000000
75%,14.000000,8.000000,25.400000,0.000000,225.750000,6.750000,30.475000,9.385000,21.000000,0.000000,0.000000,5.000000,0.000000
max,17.000000,17.000000,68.000000,3.000000,551.000000,27.000000,84.000000,36.000000,66.000000,2.000000,1.000000,17.000000,4.000000

In [74]:
df_bowling.to_csv("df_bowling_ipl22.csv")

In [53]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import cufflinks as cf
cf.go_offline()
import plotly.graph_objects as go
import plotly.express as px

In [75]:
df_bowling.drop(df_bowling.index[df_bowling['Wkts'] == 0], inplace=True)
df_bowling.drop(df_bowling.index[df_bowling['Econ'] > 13], inplace=True)

In [79]:
fig = px.scatter(df_bowling, x='Econ', y='Wkts', hover_name="Player",color = "SR", size="Ave" )
fig.show()